### ISSUE TITLE
Additional Nouns needed for Desert Dwellers

### ISSUE THREAD

**Issue by ianfhunter** [Mimic-Tools/name-generation#18]
- Create a file in `name-generation/tree/main/name-segments/nouns` called "desert.txt"
- Fill it with some desert related nouns. The context of this is for building surnames e.g. "Cosmic True**axe**", so bear this in mind

**Comment by dgabriel123** [comment]
Hello, may I grab this one?

**Comment by ianfhunter** [comment]
Certainly!
