### ISSUE TITLE
Create a simple HTML form

### ISSUE THREAD

**Issue by ianfhunter** [Mimic-Tools/name-generation#21]
The easiest way to use this tool will be through a webpage.
I have drafted a quick example of the options for configuring a character here:
[https://github.com/Mimic-Tools/name-generation/wiki/Character-Creation-Wireboard](https://github.com/Mimic-Tools/name-generation/wiki/Character-Creation-Wireboard)

Using [HTML Forms](https://www.w3schools.com/html/html_forms.asp), Create a webpage that has a form which allows you to select options for a character.

You do not have to write logic to submit the character.

**Comment by madmaxWMFU** [comment]
Hi @ianfhunter, I would love to help you, can you assign this for me?

**Comment by ianfhunter** [comment]
Certainly! Thanks :)
