### ISSUE TITLE
Additional Nouns needed for Tundra dwellers

### ISSUE THREAD

**Issue by ianfhunter** [Mimic-Tools/name-generation#24]
Create a file in name-generation/tree/main/name-segments/nouns called "tundra.txt"
Fill it with some tundra/arctic related nouns. The context of this is for building surnames e.g. "Cosmic Trueaxe", so bear this in mind

e.g. 
John White**snow**
John White**pick**
John White**tent**

**Comment by EmeraldEntities** [comment]
Hello, I can do this one.
