### ISSUE TITLE
Additional Nouns needed for Forest dwellers

### ISSUE THREAD

**Issue by ianfhunter** [Mimic-Tools/name-generation#30]
Create a file in name-generation/tree/main/name-segments/nouns called "forest.txt"
Fill it with some forest related nouns. The context of this is for building fantasy surnames e.g. "Cosmic Trueaxe", so bear this in mind

e.g.
Eve Green**wolf**
Eve Green**tree**
Eve Green**leaf**

**Comment by snehaa1989** [comment]
please assign this to me.

**Comment by olivia26** [comment]
came hear for hacktoctober fest . New to this can you help me out in case i do any mistake. I will do this task and revert back. Kindly guide me.

**Comment by ianfhunter** [comment]
Certainly Olivia. The file is already created, so if you wish you can add additional words to it
