### ISSUE TITLE
Nouns needed for Underground dwellers

### ISSUE THREAD

**Issue by ianfhunter** [Mimic-Tools/name-generation#31]
Create a file in name-generation/tree/main/name-segments/nouns called "underground.txt"
Fill it with some underground related nouns. The context of this is for building surnames e.g. "Cosmic Trueaxe", so bear this in mind

e.g.
Nora Dark**tunnel**
Nora Dark**spore**
Nora Dark**hollow**

**Comment by RimorRes** [comment]
Hi,
I'd like to try this one!

**Comment by ianfhunter** [comment]
Go for it! :)
