### ISSUE TITLE
Adjectives needed for Desert dwellers

### ISSUE THREAD

**Issue by ianfhunter** [Mimic-Tools/name-generation#32]
Create a file in name-generation/tree/main/name-segments/adjectives/ called "desert.txt"
Fill it with some adjectives relating to desert dwellers. The context of this is for building surnames e.g. "Cosmic Trueaxe", so bear this in mind

e.g.
Tom **Hot**sand
Tom **Gold**sand
Tom **Dry**sand

**Comment by Mohityadav94161** [comment]
can i work on it

**Comment by ianfhunter** [comment]
Yep! Certainly

**Comment by Mohityadav94161** [comment]
will it be counted in hacktoberfest........
I am new to open source

**Comment by ianfhunter** [comment]
Yes, if your pull request is approved or merged, it will count towards it :)
