### ISSUE TITLE
Adjectives needed for Tundra dwellers

### ISSUE THREAD

**Issue by ianfhunter** [Mimic-Tools/name-generation#38]
Create a file in name-generation/tree/main/name-segments/adjectives/ called "tundra.txt"
Fill it with some adjectives relating to desert dwellers. The context of this is for building surnames e.g. "Cosmic Trueaxe", so bear this in mind

e.g.
Tom **Cold**shovel
Tom **Ice**shovel
Tom **Frozen**shovel

**Comment by dmtrek14** [comment]
I'd like to work on this one!
