### ISSUE TITLE
Generate a report on "region" file presence/absence

### ISSUE THREAD

**Issue by ianfhunter** [Mimic-Tools/name-generation#43]
Write a small python script that will produce a textual report on what files are missing in our repository.
We can then turn these missing files into issues.

It should search for the following files:
(e.g. Mountain)
name-segments/
   adjectives/
        mountain.txt
    nouns/
         mountain.txt
     postfix/
          mountain.txt
     

Then we can view a report like the following:

| Region        | Noun | Adj |  Postfix |
| ------------- |------------- |------------- |------------- |
| Mountain      | ✓ | ✓ | ✓ |
| Aquatic     | ✓  | X | ✓ |
| Desert | ✓ | X | X |

You can either use the list here: https://github.com/Mimic-Tools/name-generation/wiki of regions, or only use ones that have existing files (preferred)

**Comment by dcorriveau** [comment]
I would like to take this if you don't mind!

**Comment by dcorriveau** [comment]
as an update, I just went ahead and completed it. Let me know if there is anything missing in the pull request :)
