### ISSUE TITLE
Change report to produce CSV instead of HTML 

### ISSUE THREAD

**Issue by ianfhunter** [Mimic-Tools/name-generation#52]
region-checker.py creates a matrix of what files are missing from our name segments.
If we change it to CSV, we'll be able to easily see it in the repo, as github supports displaying the format

Example of github supporting CSV: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

Additionally, it would nice to have a matching ✗ instead of X for the cells that do not match

**Comment by slaterslater** [comment]
Has anyone been assigned to this? If not, I'd like to be.
