### ISSUE TITLE
Add Adjectives to describe air-dwellers

### ISSUE THREAD

**Issue by ianfhunter** [Mimic-Tools/name-generation#56]
### Task
Please add some more adjectives to our air environment!

### Description
Create a file in name-generation/tree/main/name-segments/adjectives/ called air.txt if it does not exist. Then, put new adjectives into it, each on a new line.

We will use these to build names for people from those regions.

The more appropriate words the better. It's important that they be adjectives and relevant to the region.

We build names from these lists like "Cosmic Trueaxe", so think about how your word might sound as a name

All that needs to be done is to add as many appropriate words that you can think of at the ends of any of the files.

**Good examples for the air:**
John **Light**falcon
John **Fast**falcon
John **Calm**falcon

**Bad examples for the arctic/tundra:**
John Nestfalcon (Noun, not adjective)
John Hotairballoonfalcon (very long, several words, noun)
John Windyfalcon (this one is fine but as it's based on a noun, we could generate Windywind)
John Ovalfalcon (Oval has nothing to do with the arctic/tundra

**Comment by Estefyrf** [comment]
Hello @ianfhunter,
I would like to help with this issue :)

**Comment by ianfhunter** [comment]
Great! :)

**Comment by bookish** [comment]
Hello, I would like to contribute to this issue. Thank you!
