### ISSUE TITLE
Check for duplicate names in files

### ISSUE THREAD

**Issue by ianfhunter** [Mimic-Tools/name-generation#7]
It's okay if we have duplicate names in different files - the name "John" or "Mary" is common in various regions.
However, we don't want to have the same name in a single file more than once. This will skew randomness checking.

This is particularly important as the name database grows and it's hard to visually check.

Write a python script to check if any of the files in the repo contain a name more than once.

**Comment by LCVcode** [comment]
You can assign this issue to me. 

To confirm my understanding, you want each a script that will check each text file in name-segments and remove and duplicates.  Correct?

**Comment by ianfhunter** [comment]
@LCVcode exactly! :)
the only thing to watch out for is that a name can be in different files. 
e.g. John in British Names and John in American Names

**Comment by LCVcode** [comment]
Excellent!  I'll test the files independently.  Consider it done!

**Comment by LCVcode** [comment]
@ianfhunter Fixed in PR #9.
